// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(engineFFI)
import engineFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_engine_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_engine_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        // TODO: This copies the buffer. Can we read directly from a
        // Rust buffer?
        self.init(bytes: rustBuffer.data!, count: Int(rustBuffer.len))
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous go the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_PANIC: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: nil)
}

private func rustCallWithError<T>(
    _ errorHandler: @escaping (RustBuffer) throws -> Error,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> Error)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> Error)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_PANIC:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
                throw CancellationError()

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

// Public interface members begin here.


fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

fileprivate struct FfiConverterTimestamp: FfiConverterRustBuffer {
    typealias SwiftType = Date

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Date {
        let seconds: Int64 = try readInt(&buf)
        let nanoseconds: UInt32 = try readInt(&buf)
        if seconds >= 0 {
            let delta = Double(seconds) + (Double(nanoseconds) / 1.0e9)
            return Date.init(timeIntervalSince1970: delta)
        } else {
            let delta = Double(seconds) - (Double(nanoseconds) / 1.0e9)
            return Date.init(timeIntervalSince1970: delta)
        }
    }

    public static func write(_ value: Date, into buf: inout [UInt8]) {
        var delta = value.timeIntervalSince1970
        var sign: Int64 = 1
        if delta < 0 {
            // The nanoseconds portion of the epoch offset must always be
            // positive, to simplify the calculation we will use the absolute
            // value of the offset.
            sign = -1
            delta = -delta
        }
        if delta.rounded(.down) > Double(Int64.max) {
            fatalError("Timestamp overflow, exceeds max bounds supported by Uniffi")
        }
        let seconds = Int64(delta)
        let nanoseconds = UInt32((delta - Double(seconds)) * 1.0e9)
        writeInt(&buf, sign * seconds)
        writeInt(&buf, nanoseconds)
    }
}


public struct Room {
    public var roomId: String
    public var passcode: String
    public var publickeyFingerprint: String
    public var peerIp: String
    public var peerPort: UInt16
    public var fileName: String
    public var fileHash: String
    public var sent: UInt32
    public var total: UInt32
    public var createdAt: Date

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(roomId: String, passcode: String, publickeyFingerprint: String, peerIp: String, peerPort: UInt16, fileName: String, fileHash: String, sent: UInt32, total: UInt32, createdAt: Date) {
        self.roomId = roomId
        self.passcode = passcode
        self.publickeyFingerprint = publickeyFingerprint
        self.peerIp = peerIp
        self.peerPort = peerPort
        self.fileName = fileName
        self.fileHash = fileHash
        self.sent = sent
        self.total = total
        self.createdAt = createdAt
    }
}


extension Room: Equatable, Hashable {
    public static func ==(lhs: Room, rhs: Room) -> Bool {
        if lhs.roomId != rhs.roomId {
            return false
        }
        if lhs.passcode != rhs.passcode {
            return false
        }
        if lhs.publickeyFingerprint != rhs.publickeyFingerprint {
            return false
        }
        if lhs.peerIp != rhs.peerIp {
            return false
        }
        if lhs.peerPort != rhs.peerPort {
            return false
        }
        if lhs.fileName != rhs.fileName {
            return false
        }
        if lhs.fileHash != rhs.fileHash {
            return false
        }
        if lhs.sent != rhs.sent {
            return false
        }
        if lhs.total != rhs.total {
            return false
        }
        if lhs.createdAt != rhs.createdAt {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(roomId)
        hasher.combine(passcode)
        hasher.combine(publickeyFingerprint)
        hasher.combine(peerIp)
        hasher.combine(peerPort)
        hasher.combine(fileName)
        hasher.combine(fileHash)
        hasher.combine(sent)
        hasher.combine(total)
        hasher.combine(createdAt)
    }
}


public struct FfiConverterTypeRoom: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Room {
        return try Room(
            roomId: FfiConverterString.read(from: &buf), 
            passcode: FfiConverterString.read(from: &buf), 
            publickeyFingerprint: FfiConverterString.read(from: &buf), 
            peerIp: FfiConverterString.read(from: &buf), 
            peerPort: FfiConverterUInt16.read(from: &buf), 
            fileName: FfiConverterString.read(from: &buf), 
            fileHash: FfiConverterString.read(from: &buf), 
            sent: FfiConverterUInt32.read(from: &buf), 
            total: FfiConverterUInt32.read(from: &buf), 
            createdAt: FfiConverterTimestamp.read(from: &buf)
        )
    }

    public static func write(_ value: Room, into buf: inout [UInt8]) {
        FfiConverterString.write(value.roomId, into: &buf)
        FfiConverterString.write(value.passcode, into: &buf)
        FfiConverterString.write(value.publickeyFingerprint, into: &buf)
        FfiConverterString.write(value.peerIp, into: &buf)
        FfiConverterUInt16.write(value.peerPort, into: &buf)
        FfiConverterString.write(value.fileName, into: &buf)
        FfiConverterString.write(value.fileHash, into: &buf)
        FfiConverterUInt32.write(value.sent, into: &buf)
        FfiConverterUInt32.write(value.total, into: &buf)
        FfiConverterTimestamp.write(value.createdAt, into: &buf)
    }
}


public func FfiConverterTypeRoom_lift(_ buf: RustBuffer) throws -> Room {
    return try FfiConverterTypeRoom.lift(buf)
}

public func FfiConverterTypeRoom_lower(_ value: Room) -> RustBuffer {
    return FfiConverterTypeRoom.lower(value)
}

public enum EngineError {

    
    
    // Simple error enums only carry a message
    case RequestError(message: String)
    
    // Simple error enums only carry a message
    case DatabaseError(message: String)
    
    // Simple error enums only carry a message
    case TransactionError(message: String)
    
    // Simple error enums only carry a message
    case TableError(message: String)
    
    // Simple error enums only carry a message
    case StorageError(message: String)
    
    // Simple error enums only carry a message
    case CommitError(message: String)
    
    // Simple error enums only carry a message
    case DbOpenError(message: String)
    
    // Simple error enums only carry a message
    case SerdeError(message: String)
    
    // Simple error enums only carry a message
    case X509SpkiError(message: String)
    
    // Simple error enums only carry a message
    case GenerateSelfSignedCertificateError(message: String)
    
    // Simple error enums only carry a message
    case IoError(message: String)
    
    // Simple error enums only carry a message
    case HandleMessageToStunError(message: String)
    
    // Simple error enums only carry a message
    case StunNoResponse(message: String)
    
    // Simple error enums only carry a message
    case PortAlreadySet(message: String)
    
    // Simple error enums only carry a message
    case PortNotSet(message: String)
    
    // Simple error enums only carry a message
    case TlsSetupError(message: String)
    
    // Simple error enums only carry a message
    case TlsHandshakeError(message: String)
    
    // Simple error enums only carry a message
    case ConnectionError(message: String)
    

    fileprivate static func uniffiErrorHandler(_ error: RustBuffer) throws -> Error {
        return try FfiConverterTypeEngineError.lift(error)
    }
}


public struct FfiConverterTypeEngineError: FfiConverterRustBuffer {
    typealias SwiftType = EngineError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EngineError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .RequestError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .DatabaseError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .TransactionError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .TableError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .StorageError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .CommitError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .DbOpenError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 8: return .SerdeError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 9: return .X509SpkiError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 10: return .GenerateSelfSignedCertificateError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 11: return .IoError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 12: return .HandleMessageToStunError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 13: return .StunNoResponse(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 14: return .PortAlreadySet(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 15: return .PortNotSet(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 16: return .TlsSetupError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 17: return .TlsHandshakeError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 18: return .ConnectionError(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: EngineError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .RequestError(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .DatabaseError(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .TransactionError(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .TableError(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .StorageError(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .CommitError(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))
        case .DbOpenError(_ /* message is ignored*/):
            writeInt(&buf, Int32(7))
        case .SerdeError(_ /* message is ignored*/):
            writeInt(&buf, Int32(8))
        case .X509SpkiError(_ /* message is ignored*/):
            writeInt(&buf, Int32(9))
        case .GenerateSelfSignedCertificateError(_ /* message is ignored*/):
            writeInt(&buf, Int32(10))
        case .IoError(_ /* message is ignored*/):
            writeInt(&buf, Int32(11))
        case .HandleMessageToStunError(_ /* message is ignored*/):
            writeInt(&buf, Int32(12))
        case .StunNoResponse(_ /* message is ignored*/):
            writeInt(&buf, Int32(13))
        case .PortAlreadySet(_ /* message is ignored*/):
            writeInt(&buf, Int32(14))
        case .PortNotSet(_ /* message is ignored*/):
            writeInt(&buf, Int32(15))
        case .TlsSetupError(_ /* message is ignored*/):
            writeInt(&buf, Int32(16))
        case .TlsHandshakeError(_ /* message is ignored*/):
            writeInt(&buf, Int32(17))
        case .ConnectionError(_ /* message is ignored*/):
            writeInt(&buf, Int32(18))

        
        }
    }
}


extension EngineError: Equatable, Hashable {}

extension EngineError: Error { }

fileprivate struct FfiConverterSequenceTypeRoom: FfiConverterRustBuffer {
    typealias SwiftType = [Room]

    public static func write(_ value: [Room], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeRoom.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Room] {
        let len: Int32 = try readInt(&buf)
        var seq = [Room]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeRoom.read(from: &buf))
        }
        return seq
    }
}

public func configurePort(port: UInt16) throws {
    try rustCallWithError(FfiConverterTypeEngineError.lift) {
    uniffi_engine_fn_func_configure_port(
        FfiConverterUInt16.lower(port),$0)
}
}



public func createRoom(passcode: String) throws -> String {
    return try  FfiConverterString.lift(
        try rustCallWithError(FfiConverterTypeEngineError.lift) {
    uniffi_engine_fn_func_create_room(
        FfiConverterString.lower(passcode),$0)
}
    )
}

public func getRooms() throws -> [Room] {
    return try  FfiConverterSequenceTypeRoom.lift(
        try rustCallWithError(FfiConverterTypeEngineError.lift) {
    uniffi_engine_fn_func_get_rooms($0)
}
    )
}

public func joinRoom(roomId: String, passcode: String) throws -> Bool {
    return try  FfiConverterBool.lift(
        try rustCallWithError(FfiConverterTypeEngineError.lift) {
    uniffi_engine_fn_func_join_room(
        FfiConverterString.lower(roomId),
        FfiConverterString.lower(passcode),$0)
}
    )
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variables to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 24
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_engine_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_engine_checksum_func_configure_port() != 62967) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_engine_checksum_func_create_room() != 8650) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_engine_checksum_func_get_rooms() != 58138) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_engine_checksum_func_join_room() != 51323) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}